version: 1.0.0.{build}
image: Visual Studio 2017
build:
  parallel: true
  project: MilliSimFormat.SimpleScore.sln
platform:
  - Any CPU
configuration:
  - Release
environment:
  EnableNuGetPackageRestore: true
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  - nuget update -self
  - nuget restore
test:
  assemblies:
    only:
      - '**\*.Tests.dll'
